config/routes.rb
Rails.application.routes.draw do
  resources :lists 
  get "list/:id/work_new", to: "lists#new_work", as: 'new_work'
  delete "list/:list_id/work/:work_id", to: "lists#destroy_work", as: "destroy_work"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	attr_accessor :checks_elements
	attr_accessor :work_title
	has_many :works

	def save_check
		#colors_array = colors_ids.split(",")
		puts "\n\n\n entré \n\n\n"
		unless checks_elements.nil?
			checks_elements.each do |check|
				puts "\n\n\n #{check} \n\n\n"
			end
		
		end	
	end
end

app/models/work.rb
class Work < ApplicationRecord
	belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy new_work]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @works = @list.works.all

  end
    
  

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to edit_list_path(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        @list.save_check
        format.html { redirect_to edit_list_path(@list), notice: "List was successfully updated." }
        
        #redirect_to @list
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.works.destroy_all
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_work
    @list.works.create(title: "", check: false)
    redirect_to edit_list_path
  end

  def destroy_work
    work = Work.find(params[:work_id])
    work.destroy

    redirect_to edit_list_path(params[:list_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, checks_elements: [], work_title: [])
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
	def new
		@list = List.find(params[:list])
		puts "\n\n\n #{@list.id} \n\n\n"
		redirect_to edit_list_path(list)
	end

	def destroy
		work = Work.find(params[:id])
		work.destroy
		redirect_to edit_list_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntrevistaCb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="card padding margin-top">
  <%= form_with(model: list) do |form| %>
    <% if list.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>
  
        <ul>
          <% list.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <h1 class="field">
      <%= form.text_field :name %>
    </h1> 
  
    <%if @works != nil %>
      <% @works.each do |work| %>
        <% if work.check == false %>
        <div class="field">
          <%= form.check_box :checks_elements, checked:work.check %>
          <%= form.text_field :work_title, value:work.title %>
          <%= link_to 'X', destroy_work_url(list,work), method: :delete %>
        </div>
        <% end %>
      <% end %>
      <%= link_to "Agregar Tarea", new_work_url(@list) %>
      <% @works.each do |work| %>
        <% if work.check == true %>
        <div class="field">
          <%= form.check_box :checks_elements, checked:work.check %>
          <%= form.label :work_title, value:work.title, class: "tachado" %>
          <%= link_to 'X', destroy_work_url(list,work), method: :delete %>
        </div>
        <% end %>
      <% end %>

    <%end%>
         
  
    <p></p>
    <div class="actions">
      <%= form.submit "Guardar Lista", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/lists/_list.html.erb
<div class="card padding margin-top">
	<h3 class="text-uppercase"><%= list.name %></h3>

	<%= link_to "Ver más", edit_list_path(list) %>
	<%= link_to 'Eliminar', list, method: :delete %>
</div>

app/views/lists/edit.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form', list: @list %>


<%= link_to 'Volver', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listas</h1>
<br>  
  <%= render @lists %>
<br>

  <%= link_to 'Nueva Lista', new_list_path, class: "btn btn-primary" %>

app/views/lists/new.html.erb
<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/works/new.html.erb
new.html.erb